apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  selector:
    app: app
    mode: active
  type: NodePort
  ports:
    - name: app-ports
      port: 8090
      targetPort: 8082

